/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as StoryRouteImport } from './routes/story'
import { Route as UsRouteImport } from './routes/us'
import { Route as EndingIdRouteImport } from './routes/ending.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const UsRoute = UsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => rootRouteImport,
} as any)
const EndingIdRoute = EndingIdRouteImport.update({
  id: '/ending/$id',
  path: '/ending/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/story': typeof StoryRoute
  '/us': typeof UsRoute
  '/ending/$id': typeof EndingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/story': typeof StoryRoute
  '/us': typeof UsRoute
  '/ending/$id': typeof EndingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/letter': typeof LetterRoute
  '/story': typeof StoryRoute
  '/us': typeof UsRoute
  '/ending/$id': typeof EndingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/letter' | '/story' | '/us' | '/ending/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/letter' | '/story' | '/us' | '/ending/$id'
  id: '__root__' | '/' | '/letter' | '/story' | '/us' | '/ending/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LetterRoute: typeof LetterRoute
  StoryRoute: typeof StoryRoute
  UsRoute: typeof UsRoute
  EndingIdRoute: typeof EndingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us': {
      id: '/us'
      path: '/us'
      fullPath: '/us'
      preLoaderRoute: typeof UsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ending/$id': {
      id: '/ending/$id'
      path: '/ending/$id'
      fullPath: '/ending/$id'
      preLoaderRoute: typeof EndingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LetterRoute: LetterRoute,
  StoryRoute: StoryRoute,
  UsRoute: UsRoute,
  EndingIdRoute: EndingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
